### ISSUE TITLE
Ophelines 

### ISSUE THREAD

**Issue by sarahgarcin** [sarahgarcin/Forccast-publication#10]
Faire des recherches sur comment les gérer

**Comment by driceduconge** [comment]
il y a deux propriétés css dédiées aux veuves et orphelines:
[orphelines](https://developer.mozilla.org/fr/docs/Web/CSS/orphans)
[veuves](https://developer.mozilla.org/fr/docs/Web/CSS/widows)

**Comment by driceduconge** [comment]
problème: orphans et widows ne sont pas compatibles sur firefox, alors que la fonction @counter style n'est dispo que sur firefox (qui permet de faire une ol stylisée) donc c'est un choix à faire, je n'ai pas trouvé de plugin js remplaçant l'un ou l'autre...

**Comment by driceduconge** [comment]
réglé en même temps que #19

**Comment by sarahgarcin** [comment]
Peux-tu expliquer en commentaire les propriétés css utilisées pour les oprhelines ? et mettre un lien vers la doc ?

**Comment by driceduconge** [comment]
C'est exactement celles que j'ai mises plus haut:
https://developer.mozilla.org/fr/docs/Web/CSS/orphans
et https://developer.mozilla.org/fr/docs/Web/CSS/widows
