### ISSUE TITLE
Problème d'alignement des numéros de page 

### ISSUE THREAD

**Issue by sarahgarcin** [sarahgarcin/Forccast-publication#13]

**Comment by driceduconge** [comment]
Si les numéros sont trop loin c'est car ils étaient dans `@bottom-right-corner` j'ai donc changé ce dernier (pas sur le repo, en perso) en `@bottom-right` dans chaque endroit des css _main_styles, part-one/two/three et ouverture_ je n'arrive pas à les bouger sans "casser" le système de couleurs et d'apparitions disparitions de la numérotation en fonction de si la page est :blank...
il y a peut être un truc dans le js?
```
@page {
  size: 165mm 205mm;

  @bottom-right {  content: counter(page);
   font-size: 9pt;
   font-weight: bold;
 	}

 	@bottom-left {
 		content: string(title) ' -> ' string(subtitle);
    font-size: 9pt;
   	font-weight: bold;
  }
}

@page :left {
  margin: 10mm 8.5mm 18mm 50mm;
}

@page :right {
  margin: 10mm 10mm 18mm 50mm;
}


@page:blank{
	@bottom-right {
   content: none;
 	}

 	@bottom-left {
 		content: none;
 	}
}
```

**Comment by sarahgarcin** [comment]
J'ai réglé le problème.
Effectivement il suffisait d'enlever `corner` sur `@bottom-right-corner` dans tous les fichiers css
