### ISSUE TITLE
mettre les + sur interpages

### ISSUE THREAD

**Issue by driceduconge** [sarahgarcin/Forccast-publication#17]
exemple:
<img width="1052" alt="manque_+" src="https://user-images.githubusercontent.com/64810518/94267867-97e96f00-ff3c-11ea-9c55-a878f3df7a98.PNG">

**Comment by sarahgarcin** [comment]
Normalement ça marche.
Les + s'ajoutent à la fin après que tout le contenu soit chargé (ça peut prendre un peu de temps).
