### ISSUE TITLE
problèmes sommaire

### ISSUE THREAD

**Issue by driceduconge** [sarahgarcin/Forccast-publication#21]
balisage mal fait !

en effet:
- les sections de la p1 sont mal emboîté : 
on se retrouve avec TITRE.SousTitre.section.section.SOUSTITRE.section
- il manque les numéros de pages (après les TITRES et Sous Titres seulement)
- il faut qu'on ait la possibilité d'avoir une classe spéciale pour chaque partie dans le sommaire (pour leur donner leurs couleurs respectives)

**Comment by driceduconge** [comment]
je le vois bien comme ça le sommaire:
<img width="993" alt="sommaire" src="https://user-images.githubusercontent.com/64810518/94454157-cf148600-01b1-11eb-9bf7-834bbfe8aff3.PNG">

**Comment by sarahgarcin** [comment]
à tester comme alternative: 
https://gitlab.pagedmedia.org/tools/experiments/tree/master/table-of-content

**Comment by driceduconge** [comment]
- bizarrement il n'y a pas la même marge sur les deux pages du sommaire
- conclusion n'a pas de numéro de page (aucune idée pourquoi)
<img width="816" alt="pb sommaire" src="https://user-images.githubusercontent.com/64810518/94670238-950ec580-0312-11eb-850f-a826eeedb71b.PNG">
