### ISSUE TITLE
Faire des recherchers sur les espaces dans un texte justifié sur le web 

### ISSUE THREAD

**Issue by sarahgarcin** [sarahgarcin/Forccast-publication#8]

**Comment by driceduconge** [comment]
Après quelques recherches on a certains outils à disposition qui peuvent aider à résoudre les problèmes qu'on peut rencontrer avec du css.
C'est des choses que tu connais déjà probablement je liste ici quand même au cas où:
[text-justify](https://developer.mozilla.org/fr/docs/Web/CSS/text-justify)
[white-space](https://developer.mozilla.org/fr/docs/Web/CSS/white-space), celui là je suis pas trop sûr mais bon ça peut être pour certains cas.
[hanging-punctuation](https://developer.mozilla.org/fr/docs/Web/CSS/hanging-punctuation), pas supporté par firefox mais ça peut peut être être tentable de l'utiliser?
 et donc [hanging punctuation github](https://github.com/kennethormandy/hanging-punctuation), qui est un polyfill qui simule la fonction hanging punctuation => ça nous ferait gagner de l'espace sur les guillements et c'est + beau.

**Comment by sarahgarcin** [comment]
Solution choisie: Hyphenopoly
https://github.com/mnater/Hyphenopoly
